const express = require('express')
const admin = require('../controllers/admin')
const verify = require('../middlewares/auth/verifyAdmin')
const router = express.Router()

router.post('/login', admin.login)
router.get('/logout', verify, admin.logout)
router.get('/', verify, admin.getAdminInfo)
router.get('/profile', verify, admin.getAdminInfo)
router.get('/transactions', verify, admin.getTransactions)
router.get('/feedbacks', verify, admin.getFeedbacks)
router.get('/feedbacks/:id/delete', verify, admin.deleteFeedbacks)
router.post('/transactions/userId', verify, admin.getTransactionById)
router.get('/unregisteredUsers', verify, admin.getUnregisteredUsers)
router.get('/unregisteredUsers/:userId', verify, admin.getUserDetails)
router.get('/unregisteredUsers/:userId/accept', verify, admin.acceptUser)
router.get('/unregisteredUsers/:userId/reject', verify, admin.rejectUser)
router.post('/search', verify, admin.searchUser)
router.post('/users/:userId/update', verify, admin.updateByUserId)
router.get('/users/:userId/delete', verify, admin.deleteByUserId)

module.exports = router